
NBs = grid-predict.ipynb coordinates.ipynb Interferometry.ipynb wimaging.ipynb \
  wsnapshot.ipynb aaf.ipynb aimaging.ipynb awtowers.ipynb facet-subgrid.ipynb \
  facet-subgrid-impl.ipynb predict.ipynb \
  wtowers.ipynb wtowers-predict.ipynb

include ../jupyter.mk
