
NBs = coordinates.ipynb Interferometry.ipynb wkernel.ipynb wimaging.ipynb \
  wsnapshot.ipynb aaf.ipynb aimaging.iypnb awtowers.ipynb facet-subgrid.ipynb \
  facet-subgrid-imply.ipynb grid-predict.ipynb predict.ipynb \
  wtowers.ipynb wtowers-predict.ipynb

include ../jupyter.mk
